name: IaC Deployment
on: [push]

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ansible Playbook
        run: |
          sudo apt update && sudo apt install ansible -y
          cd iac/ansible
          ansible-playbook playbook.yml